#!/bin/bash  

# Creates the asset_manifest_json.php needed for ReactPress admin
  
asset_manifest_json=`cat build/asset-manifest.json`  
echo "<?php
// This is an autogenerated file, please don't touch.
\$asset_manifest_json = <<<'HEREA'
$asset_manifest_json
HEREA;"  > build/asset-manifest.php